### ISSUE TITLE
New feature: Automatically find the most recent gcc and binutils versions

### ISSUE THREAD

**Issue by ChrisSwinchatt** [ChrisSwinchatt/XGCC#3]

**Comment by mathieu-aubin** [comment]
This command could help you, assuming ${1} is not empty and is url-ish...

```shell
function _getVER() {
	head -n1 <(
		curl -sLk "${1}" |
		grep --color=never -Pio \
		"\K(?:\d+\.)(?:\d+\.)(?:\*|\d+)" |
		sort -Vr
	)
}
```

This is a very basic Perl regex that doesn't truly do justice to semantic version system. It also doesn't take any '-rcX|-betaX'.

here is a cast to show it working (at least with the one url)

[![asciicast](https://asciinema.org/a/214520.svg)](https://asciinema.org/a/214520)

**Comment by ChrisSwinchatt** [comment]
@mathieu-aubin 

That's pretty slick, make a pull request if you like.

**Comment by mathieu-aubin** [comment]
You are welcome to use it in any way you see fit.
Seems to be somewhat working for most if not all of the gnu tools.
let me know if you end up making it better/more reliable
